FROM jenkins/jenkins:2.472-jdk21

USER jenkins
RUN jenkins-plugin-cli --plugins pipeline-stage-view:2.34 pipeline-graph-view:313.v1322ce83d680 build-timestamp:1.0.3 timestamper:1.17 pollscm:1.5 github-api:1.321-475.vf7ef62885c83 github-branch-source:1793.v1831e9c68d77


USER root
ENV FLUENTD_HOST "fluentd"
ENV FLUENTD_PORT "24224"
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
ENV JENKINS_URL "http://jenkins:10000"
ENV ACCESS_KEY ${ACCESS_KEY}
ENV SECRET_KEY ${SECRET_KEY}

COPY ./requirements.txt requirements.txt

RUN apt update && \
	apt install -y python3.11 python3-pip
RUN pip3 install --upgrade pip --break-system-packages && \ 
	pip install -r requirements.txt --break-system-packages

COPY jenkins/1-configureJenkins.groovy /usr/share/jenkins/ref/init.groovy.d/1-configureJenkins.groovy
COPY jenkins/2-addAccessKeys.groovy /usr/share/jenkins/ref/init.groovy.d/2-addAccessKeys.groovy
